rules:
  - args:
      - type: Context
        index: 0
        pkg: context
      - type: TenantID
        index: 1
        pkg: github.com/nametake/mustargs
    file_patterns:
      - usecase/tenant_*.go
      - mysql/tenant_*.go
    ignore_file_patterns:
      - .*_gen.go
    func_patterns:
      - Get.*
      - Update.*
    ignore_func_patterns:
      - ^New.*
    recv_patterns:
      - ^Tenant.*Usecase$
      - ^Tenant.*DB$
    ignore_recv_patterns:
      - ^TenantDBDebug$
